import { SortTaskQueryParameters } from './sort-task-query-parameters';
import { VariableQueryParameter } from './variable-query-parameter';

export interface TaskQuery {
  processInstanceId?: string;
  processInstanceIdIn?: string[];
  processInstanceBusinessKey?: string;
  processInstanceBusinessKeyExpression?: string;
  processInstanceBusinessKeyIn?: string[];
  processInstanceBusinessKeyLike?: string;
  processInstanceBusinessKeyLikeExpression?: string;
  processDefinitionId?: string;
  processDefinitionKey?: string;
  processDefinitionKeyIn?: string[];
  processDefinitionName?: string;
  processDefinitionNameLike?: string;
  executionId?: string;
  caseInstanceId?: string;
  caseInstanceBusinessKey?: string;
  caseInstanceBusinessKeyLike?: string;
  caseDefinitionId?: string;
  caseDefinitionKey?: string;
  caseDefinitionName?: string;
  caseDefinitionNameLike?: string;
  caseExecutionId?: string;
  activityInstanceIdIn?: string[];
  tenantIdIn?: string[];
  withoutTenantId?: boolean;
  assignee?: string;
  assigneeExpression?: string;
  assigneeLike?: string;
  assigneeLikeExpression?: string;
  assigneeIn?: string[];
  owner?: string;
  ownerExpression?: string;
  candidateGroup?: string;
  candidateGroupExpression?: string;
  candidateUser?: string;
  candidateUserExpression?: string;
  includeAssignedTasks?: boolean;
  involvedUser?: string;
  involvedUserExpression?: string;
  assigned?: boolean;
  unassigned?: boolean;
  taskDefinitionKey?: string;
  taskDefinitionKeyIn?: string[];
  taskDefinitionKeyLike?: string;
  name?: string;
  nameNotEqual?: string;
  nameLike?: string;
  nameNotLike?: string;
  description?: string;
  descriptionLike?: string;
  priority?: number;
  maxPriority?: number;
  minPriority?: number;
  dueDate?: string;
  dueDateExpression?: string;
  dueAfter?: string;
  dueAfterExpression?: string;
  dueBefore?: string;
  dueBeforeExpression?: string;
  followUpDate?: string;
  followUpDateExpression?: string;
  followUpAfter?: string;
  followUpAfterExpression?: string;
  followUpBefore?: string;
  followUpBeforeExpression?: string;
  followUpBeforeOrNotExistent?: string;
  followUpBeforeOrNotExistentExpression?: string;
  createdOn?: string;
  createdOnExpression?: string;
  createdAfter?: string;
  createdAfterExpression?: string;
  createdBefore?: string;
  createdBeforeExpression?: string;
  delegationState?: string;
  candidateGroups?: string[];
  candidateGroupsExpression?: string;
  withCandidateGroups?: boolean;
  withoutCandidateGroups?: boolean;
  withCandidateUsers?: boolean;
  withoutCandidateUsers?: boolean;
  active?: boolean;
  suspended?: boolean;
  taskVariables?: VariableQueryParameter[];
  processVariables?: VariableQueryParameter[];
  caseInstanceVariables?: VariableQueryParameter[];
  variableNamesIgnoreCase?: boolean;
  variableValuesIgnoreCase?: boolean;
  parentTaskId?: string;
  orQueries?: TaskQuery[];
  sorting?: {
    sortBy?:
      | 'instanceId'
      | 'caseInstanceId'
      | 'dueDate'
      | 'executionId'
      | 'caseExecutionId'
      | 'assignee'
      | 'created'
      | 'description'
      | 'id'
      | 'name'
      | 'nameCaseInsensitive'
      | 'priority'
      | 'processVariable'
      | 'executionVariable'
      | 'taskVariable'
      | 'caseExecutionVariable'
      | 'caseInstanceVariable';
    sortOrder?: 'asc' | 'desc';
    parameters?: SortTaskQueryParameters;
  }[];
}
