name: Release

on:
  push:
    tags:
      - '*'

env:
  NODE_VERSION: 14.x

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Update Version Number
        run: |
          find . -name package.json -exec sed -i "s/\"version\": \"0.0.0-CURO\",/\"version\": \"${{ steps.get_version.outputs.VERSION }}\",/g" {} \;

      - run: npm ci
      - run: npm run build.libs
      - run: npm publish
        working-directory: dist/core
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: npm run docs
      - name: Upload Docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: dist/docs
          retention-days: 1

  wiki:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
      - name: check wiki repo content
        run: |
          ls -al
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          name: docs
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "docs: generate docs"
      - name: Push changes to wiki repo
        run: |
          echo "${{ secrets.WIKI_SSH }}" > id_rsa
          GIT_SSH_COMMAND="ssh -i id_rsa" git push origin master
